name: CI/CD Advanced (O)

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump (patch|minor|major|none)"
        required: false
        default: "patch"
      simulate_fail_prod:
        description: "Simulate a failure in production to demo rollback"
        type: boolean
        default: false
permissions:
  contents: write
concurrency:
  group: advanced-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
    outputs:
      version: ${{ steps.ver.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Show Node version
        run: node -v || echo "node not available (should not happen)"
      - name: Resolve version
        id: ver
        run: |
          if [ -f package.json ]; then
            V=$(node -p "require('./package.json').version || '0.0.0'") || V="0.0.0"
          else
            V=$(date +%Y.%m.%d-%H%M)
          fi
          echo "version=$V" >> "$GITHUB_OUTPUT"
          echo "Using version: $V"
      - name: Install deps (optional)
        run: |
          if [ -f package.json ]; then
            npm ci || npm install || true
          else
            echo "No package.json — skipping npm install"
          fi
      - name: Lint (optional)
        run: |
          if [ -f package.json ]; then
            npm run lint || echo "no lint configured"
          else
            echo "Skipping lint (no package.json)"
          fi
      - name: Tests (optional smoke)
        run: |
          if [ -f package.json ]; then
            npm test || node -e "console.log('smoke test ok')"
          else
            node -e "console.log('smoke test ok (no package.json)')"
          fi
      - name: Build (optional)
        run: |
          if [ -f package.json ]; then
            npm run build || echo "no build step"
          else
            echo "No package.json — nothing to build"
          fi

      - name: Zip repository
        run: zip -r build.zip . -x ".git/*" || echo "zip finished (or nothing to zip)"

      - name: Upload artifact (versioned)
        if: matrix.node == 20 
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ steps.ver.outputs.version }}
          path: build.zip

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ needs.build.outputs.version }}

      - name: Release Staging
        uses: softprops/action-gh-release@v2
        with:
          tag_name: staging-v${{ needs.build.outputs.version }}
          name: staging-v${{ needs.build.outputs.version }}
          body: ${{ vars.RELEASE_NOTE }}
          files: build.zip
          prerelease: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify (Slack or Job Summary)
        if: always()
        env:
          WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          if [ -n "$WEBHOOK" ]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"Staging deployed: staging-v${{ needs.build.outputs.version }}\"}" \
              "$WEBHOOK" || true
          fi
          echo "Staging deployed: staging-v${{ needs.build.outputs.version }}" >> $GITHUB_STEP_SUMMARY

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ needs.build.outputs.version }}

      - name: Optional failure (for rollback demo)
        if: ${{ github.event.inputs.simulate_fail_prod == true }}
        run: |
          echo "Simulating prod failure to trigger rollback"
          exit 1

      - name: Release Production
        uses: softprops/action-gh-release@v2
        with:
          tag_name: prod-v${{ needs.build.outputs.version }}
          name: prod-v${{ needs.build.outputs.version }}
          body: ${{ vars.RELEASE_NOTE }}
          files: build.zip
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify (Slack or Job Summary)
        if: always()
        env:
          WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          if [ -n "$WEBHOOK" ]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"Production deployed: prod-v${{ needs.build.outputs.version }}\"}" \
              "$WEBHOOK" || true
          fi
          echo "Production deployed: prod-v${{ needs.build.outputs.version }}" >> $GITHUB_STEP_SUMMARY

      - name: Rollback on failure (delete release + tag)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const tag  = `prod-v${{ needs.build.outputs.version }}`;
            try {
              const rel = await github.rest.repos.getReleaseByTag({ owner, repo, tag });
              await github.rest.repos.deleteRelease({ owner, repo, release_id: rel.data.id });
              core.info(`Deleted release for ${tag}`);
            } catch (e) {
              core.warning(`No release to delete for ${tag}: ${e.message}`);
            }
            try {
              await github.rest.git.deleteRef({ owner, repo, ref: `tags/${tag}` });
              core.info(`Deleted tag ${tag}`);
            } catch (e) {
              core.warning(`No tag ref to delete for ${tag}: ${e.message}`);
            }
