name: CI/CD Advanced (O)

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump (patch|minor|major|none)"
        required: false
        default: "patch"
      simulate_fail_prod:
        description: "Simulate a failure in production to demo rollback"
        type: boolean
        default: false

permissions:
  contents: write

concurrency:
  group: advanced-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
    outputs:
      version: ${{ steps.ver.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Resolve version
        id: ver
        run: |
          if [ -f package.json ]; then
            V=$(node -p "require('./package.json').version || ''")
          else
            V=""
          fi
          # Fallback estable si no hay version
          if [ -z "$V" ]; then V="${GITHUB_RUN_NUMBER}"; fi
          echo "version=$V" >> "$GITHUB_OUTPUT"
          echo "Using version: $V"

      - name: Install deps (optional)
        run: |
          if [ -f package.json ]; then
            npm ci || npm install || true
          else
            echo "No package.json — skipping npm install"
          fi

      - name: Lint (optional)
        run: |
          if [ -f package.json ]; then
            npm run lint || echo "no lint configured"
          else
            echo "Skipping lint (no package.json)"
          fi

      - name: Tests (optional smoke)
        run: |
          if [ -f package.json ]; then
            npm test || node -e "console.log('smoke test ok')"
          else
            node -e "console.log('smoke test ok (no package.json)')"
          fi

      - name: Auto-bump (optional & tolerant)
        if: ${{ github.event.inputs.bump != 'none' && github.ref == 'refs/heads/master' && hashFiles('package.json') != '' }}
        continue-on-error: true
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --unshallow || true
          npm version ${{ github.event.inputs.bump }} -m "ci: bump %s [skip ci]" || true
          git push --follow-tags || echo "push skipped (branch protection or fork)"

      - name: Build (optional)
        run: |
          if [ -f package.json ]; then
            npm run build || echo "no build step"
          else
            echo "No package.json — nothing to build"
          fi
          zip -r build.zip . -x ".git/*"

      # ✅ subir una sola vez (Node 20) y con NOMBRE FIJO "build"
      - name: Upload artifact (single, fixed name)
        if: matrix.node == 20
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.zip

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: write
    steps:
      - name: Set VERSION env
        run: echo "VERSION=${{ needs.build.outputs.version || github.run_number }}" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build   # <-- nombre fijo

      - name: Release Staging
        uses: softprops/action-gh-release@v2
        with:
          tag_name: staging-v${{ env.VERSION }}
          name: staging-v${{ env.VERSION }}
          body: ${{ vars.RELEASE_NOTE }}
          files: build.zip
          prerelease: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify (Slack or Job Summary)
        if: always()
        env:
          WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          if [ -n "$WEBHOOK" ]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"Staging deployed: staging-v${{ env.VERSION }}\"}" \
              "$WEBHOOK" || true
          fi
          echo "Staging deployed: staging-v${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - name: Set VERSION env
        run: echo "VERSION=${{ needs.build.outputs.version || github.run_number }}" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build   # <-- nombre fijo

      - name: Optional failure (for rollback demo)
        if: ${{ github.event.inputs.simulate_fail_prod == true }}
        run: |
          echo "Simulating prod failure to trigger rollback"
          exit 1

      - name: Release Production
        uses: softprops/action-gh-release@v2
        with:
          tag_name: prod-v${{ env.VERSION }}
          name: prod-v${{ env.VERSION }}
          body: ${{ vars.RELEASE_NOTE }}
          files: build.zip
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify (Slack or Job Summary)
        if: always()
        env:
          WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          if [ -n "$WEBHOOK" ]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"Production deployed: prod-v${{ env.VERSION }}\"}" \
              "$WEBHOOK" || true
          fi
          echo "Production deployed: prod-v${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY

      - name: Rollback on failure (delete release + tag)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const tag  = `prod-v${process.env.VERSION}`;
            try {
              const rel = await github.rest.repos.getReleaseByTag({ owner, repo, tag });
              await github.rest.repos.deleteRelease({ owner, repo, release_id: rel.data.id });
              core.info(`Deleted release for ${tag}`);
            } catch (e) {
              core.warning(`No release to delete for ${tag}: ${e.message}`);
            }
            try {
              await github.rest.git.deleteRef({ owner, repo, ref: `tags/${tag}` });
              core.info(`Deleted tag ${tag}`);
            } catch (e) {
              core.warning(`No tag ref to delete for ${tag}: ${e.message}`);
            }
